export const dummyPosts = [
  {
    id: 1,
    title: "How Knowledge of Languages Is More Valuable. The Subtle Art of Writing Clean Code",
    subtitle: "It's not a skill issue, but a marketing issue",
    author: "Benben",
    date: "2025-09-20",
    category: "Language Lab",
    image: "https://picsum.photos/seed/post1/200/200",
    profileImage: "https://i.pravatar.cc/40?img=1",
    likes: 54,
    comments: 12,
  },
  {
    id: 2,
    title: "Welcome To Dream-Driven Development",
    subtitle: "Where Nothing Works",
    author: "Attila Vidács",
    date: "2025-09-22",
    category: "Gaming",
    image: "https://picsum.photos/seed/post2/200/200",
    profileImage: "https://i.pravatar.cc/40?img=2",
    likes: 120,
    comments: 8,
  },
  {
    id: 3,
    title: "Scaling React Apps Without Losing Your Mind",
    subtitle: "Architecture patterns that work in real life",
    author: "Jane Doe",
    date: "2025-09-18",
    category: "Language Lab",
    image: "https://picsum.photos/seed/post3/200/200",
    profileImage: "https://i.pravatar.cc/40?img=3",
    likes: 78,
    comments: 15,
  },
  {
    id: 4,
    title: "AI in 2025: Trends Developers Should Know",
    subtitle: "Staying ahead in a fast-changing industry",
    author: "Samuel Green",
    date: "2025-09-12",
    image: "https://picsum.photos/seed/post4/200/200",
    profileImage: "https://i.pravatar.cc/40?img=4",
    likes: 95,
    comments: 20,
  },
  {
    id: 5,
    title: "The Subtle Art of Writing Clean Code",
    subtitle: "Small habits that lead to big improvements",
    author: "Emily Carter",
    date: "2025-09-10",
    image: "https://picsum.photos/seed/post5/200/200",
    profileImage: "https://i.pravatar.cc/40?img=5",
    likes: 200,
    comments: 35,
  },
  {
    id: 6,
    title: "Remote Work in Tech: Still the Future?",
    subtitle: "Exploring pros and cons in 2025",
    author: "Alex Tan",
    date: "2025-09-05",
    image: "https://picsum.photos/seed/post6/200/200",
    profileImage: "https://i.pravatar.cc/40?img=6",
    likes: 143,
    comments: 18,
  },
  {
    id: 7,
    title: "Breaking Down Web3 Myths",
    subtitle: "Separating hype from reality",
    author: "Lara Smith",
    category: "Blockchain",
    date: "2025-08-30",
    image: "https://picsum.photos/seed/post7/200/200",
    profileImage: "https://i.pravatar.cc/40?img=7",
    likes: 64,
    comments: 10,
  },
  {
    id: 8,
    title: "Why Testing Is Your Best Friend",
    subtitle: "A developer’s guide to sanity",
    author: "Michael Osei",
    category: "Programming",
    date: "2025-08-25",
    image: "https://picsum.photos/seed/post8/200/200",
    profileImage: "https://i.pravatar.cc/40?img=8",
    likes: 180,
    comments: 22,
  },
];



export const dummyStaffs = [
  {
    id: 1,
    title: "How Knowledge of Languages Is More Valuable. The Subtle Art of Writing Clean Code",
    subtitle: "It's not a skill issue, but a marketing issue",
    author: "Benben",
    date: "2025-09-20",
    category: "Language Lab",
    profileImage: "https://i.pravatar.cc/40?img=1",
 
  },
  {
    id: 2,
    title: "Welcome To Dream-Driven Development",
    subtitle: "Where Nothing Works",
    author: "Attila Vidács",
    date: "2025-09-22",
    category: "Game Development",
    profileImage: "https://i.pravatar.cc/40?img=2",
   
  },
  {
    id: 3,
    title: "Scaling React Apps Without Losing Your Mind",
    subtitle: "Architecture patterns that work in real life",
    author: "Jane Doe",
    date: "2025-09-18",
    category: "Language Lab",
    profileImage: "https://i.pravatar.cc/40?img=3",
    
  },
  {
    id: 4,
    title: "AI in 2025: Trends Developers Should Know",
    subtitle: "Staying ahead in a fast-changing industry",
    author: "Samuel Green",
    date: "2025-09-12",
    profileImage: "https://i.pravatar.cc/40?img=4",
    
  },

];
